version: '2'

services:
  database:
    container_name: database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
      - 33070:33060
    environment:
      MYSQL_DATABASE: techchallenge
      MYSQL_ROOT_PASSWORD: senha
    volumes:
      - /tmp/fiap-restaurant-app/mysql:/var/lib/mysql
