apiVersion: v1
kind: Service
metadata:
  name: app-restaurant-mysql-service
spec:
  ports:
    - port: 3306
  selector:
    app: app-restaurant-mysql
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-restaurant-mysql
spec:
  selector:
    matchLabels:
      app: app-restaurant-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app-restaurant-mysql
    spec:
      containers:
        - image: mysql:8.1
          name: app-restaurant-mysql
          env:
            - name: MYSQL_DATABASE
              value: techchallenge
            - name: MYSQL_ROOT_PASSWORD
              value: senha
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
