name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: AWS EKS Kubeconfig
        run: aws eks update-kubeconfig --name app-restaurant-cluster --region us-east-1

      - name: DockerHub login
        run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASS }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USER }}/app-restaurant

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USER }}/app-restaurant

      - name: Deploy on EKS
        run: |
          kubectl apply -f k8s-mysql.yaml
          kubectl apply -f k8s-app.yaml
